version: '3'

services:
  red:
    restart: unless-stopped
    image: redis
    entrypoint: redis-server --appendonly yes
    volumes:
      - ./.redis:/data
    ports:
      - "6379:6379"
  hanabi:
    build: .
    restart: always
  #  image: hanabi
    ports:
      - "8080:8080"
